# Generated by Django 3.2 on 2024-05-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('background', models.TextField()),
                ('summary', models.TextField()),
                ('cast', models.TextField()),
                ('analysis', models.TextField()),
                ('scenes', models.TextField()),
                ('review', models.TextField()),
                ('impact', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
