# Generated by Django 3.2 on 2024-05-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0002_moviedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='cast',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='impact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='scenes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
